name: GoodDeservesGreat
favicon: null
layout_spectrum: 0.75667
typography_spectrum: 0.5677
title: Good Work Deserves Great Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6beb4'
    - '#ad514c'
    - '#11467a'
    - '#78e1dd'
    - '#4b7dae'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
