name: GoodDeservesGreat
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8181645029690117
title: Good Work Deserves Great Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33423f'
    - '#778183'
    - '#fdfefe'
    - '#a3acab'
    - '#c5c7c6'
  brandStrength: 0.75
  lightness: 0.4924435378052294
  saturation: 0.4870489090681076
  rhythmicContrast: 0.8991007353179157
purpose: []
