name: GoodDeservesGreat
favicon: null
layout_spectrum: 0.99032
typography_spectrum: 0.5677
title: Good Work Deserves Great Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00120b'
    - '#553d36'
    - '#6b818c'
    - '#d8e4ff'
    - '#78e0dc'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
