name: GoodDeservesGreat
favicon: null
layout_spectrum: 0.99032
typography_spectrum: 0.5677
title: Good Work Deserves Great Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33423f'
    - '#778183'
    - '#fdfefe'
    - '#a3acab'
    - '#c5c7c6'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
